id: PB4CF3631
initial_creation_type: input
source_metadata:
  title: Ratna Lingpa Series
  language: en
  description: 'Texts by the famous treasure-revealer Ratna Lingpa (ratna gling pa,
    1403-1479):'
  volume:
    dd517b0c580340e5ba654e3d71d3836a:
      title: 'Cloud Banks of Blessings: A Prayer Recounting the Eleven Deeds of the
        Life and Liberation of the Guru from Uḍḍiyāna'
      parent: Guru Padmasambhava
    9c947db27fc44ac49a4271cb495511b4:
      title: The Invocation of Uḍḍiyāna on the Tenth Day
      parent: Guru Padmasambhava
    86678122493549429925a10b1a394dac:
      title: Aspiration Prayer from Tārā Sādhana
      parent: Tārā
created_at: '2022-03-01T01:19:45.926672'
last_modified_at: '2022-03-01T01:19:45.926678'
